-- Disable RLS so the app works. Re-enable later when policies are sorted.
ALTER TABLE profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE boxes DISABLE ROW LEVEL SECURITY;
ALTER TABLE items DISABLE ROW LEVEL SECURITY;
ALTER TABLE item_types DISABLE ROW LEVEL SECURITY;
ALTER TABLE box_collaborators DISABLE ROW LEVEL SECURITY;
